// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantAPI.Context;

#nullable disable

namespace RestaurantAPI.Migrations
{
    [DbContext(typeof(APIContext))]
    partial class APIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RestaurantAPI.Entities.About", b =>
                {
                    b.Property<int>("AboutID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AboutID"), 1L, 1);

                    b.Property<byte[]>("AboutCompanyLogo")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("AboutCompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AboutDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("AboutImage1")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("AboutImage2")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("AboutReportImage")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("AboutRezervationImage")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("AboutWhyChoose")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("AboutID");

                    b.ToTable("Abouts");

                    b.HasData(
                        new
                        {
                            AboutID = 1,
                            AboutCompanyLogo = new byte[0],
                            AboutCompanyName = "",
                            AboutDesc = "",
                            AboutImage1 = new byte[0],
                            AboutImage2 = new byte[0],
                            AboutReportImage = new byte[0],
                            AboutRezervationImage = new byte[0],
                            AboutWhyChoose = ""
                        });
                });

            modelBuilder.Entity("RestaurantAPI.Entities.AdminLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"), 1L, 1);

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("LogMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LogUserGeo")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("LogUserIPAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("LogUserInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("LogID");

                    b.ToTable("AdminLogs");
                });

            modelBuilder.Entity("RestaurantAPI.Entities.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("CategoryStatus")
                        .HasColumnType("bit");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("RestaurantAPI.Entities.Chef", b =>
                {
                    b.Property<int>("ChefID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChefID"), 1L, 1);

                    b.Property<string>("ChefDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChefFacebookLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("ChefImage")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ChefInstagramLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ChefLinkedinLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ChefNameSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("ChefStatus")
                        .HasColumnType("bit");

                    b.Property<string>("ChefTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ChefTwitterLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ChefID");

                    b.ToTable("Chefs");
                });

            modelBuilder.Entity("RestaurantAPI.Entities.CompanyInfo", b =>
                {
                    b.Property<int>("CompanyInfoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyInfoID"), 1L, 1);

                    b.Property<string>("CompanyInfoAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CompanyInfoGithubLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyInfoIFrame")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CompanyInfoInstagramLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyInfoLinkedinLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyInfoMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyInfoOpenClosed")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyInfoPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("CompanyInfoWebSiteLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CompanyInfoID");

                    b.ToTable("CompanyInfos");

                    b.HasData(
                        new
                        {
                            CompanyInfoID = 1,
                            CompanyInfoAddress = "",
                            CompanyInfoGithubLink = "",
                            CompanyInfoIFrame = "",
                            CompanyInfoInstagramLink = "",
                            CompanyInfoLinkedinLink = "",
                            CompanyInfoMail = "",
                            CompanyInfoOpenClosed = "",
                            CompanyInfoPhone = "",
                            CompanyInfoWebSiteLink = ""
                        });
                });

            modelBuilder.Entity("RestaurantAPI.Entities.Email", b =>
                {
                    b.Property<int>("EmailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmailID"), 1L, 1);

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmailBox")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmailCompanyName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("EmailImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("EmailPassword")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmailPhone")
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("EmailPort")
                        .HasColumnType("int");

                    b.Property<int>("EmailSSl")
                        .HasColumnType("int");

                    b.Property<string>("EmailServer")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EmailID");

                    b.ToTable("Emails");

                    b.HasData(
                        new
                        {
                            EmailID = 1,
                            EmailAddress = "",
                            EmailBox = "",
                            EmailCompanyName = "",
                            EmailImage = new byte[0],
                            EmailPassword = "",
                            EmailPhone = "",
                            EmailPort = 0,
                            EmailSSl = 0,
                            EmailServer = ""
                        });
                });

            modelBuilder.Entity("RestaurantAPI.Entities.Event", b =>
                {
                    b.Property<int>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventID"), 1L, 1);

                    b.Property<string>("EventDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("EventImage")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("EventPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EventPriceSembol")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<bool>("EventStatus")
                        .HasColumnType("bit");

                    b.HasKey("EventID");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("RestaurantAPI.Entities.Feature", b =>
                {
                    b.Property<int>("FeatureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeatureID"), 1L, 1);

                    b.Property<string>("FeatureDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte[]>("FeatureImageData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FeatureSubTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FeatureTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FeatureVideoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("FeatureID");

                    b.ToTable("Features");

                    b.HasData(
                        new
                        {
                            FeatureID = 1,
                            FeatureDescription = "",
                            FeatureImageData = new byte[0],
                            FeatureSubTitle = "",
                            FeatureTitle = "",
                            FeatureVideoUrl = ""
                        });
                });

            modelBuilder.Entity("RestaurantAPI.Entities.GalleryImage", b =>
                {
                    b.Property<int>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageID"), 1L, 1);

                    b.Property<byte[]>("ImageByte")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("ImageStatus")
                        .HasColumnType("bit");

                    b.Property<string>("ImageTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ImageID");

                    b.ToTable("GalleryImages");
                });

            modelBuilder.Entity("RestaurantAPI.Entities.Icon", b =>
                {
                    b.Property<int>("IconID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IconID"), 1L, 1);

                    b.Property<bool>("IconStatus")
                        .HasColumnType("bit");

                    b.Property<string>("IconURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IconID");

                    b.ToTable("Icons");
                });

            modelBuilder.Entity("RestaurantAPI.Entities.Message", b =>
                {
                    b.Property<int>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageID"), 1L, 1);

                    b.Property<string>("MessageDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("MessageIsRead")
                        .HasColumnType("bit");

                    b.Property<string>("MessageNameSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MessagePhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime>("MessageSendDate")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("MessageSubject")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("WebLogUserGeo")
                        .IsRequired()
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("WebLogUserIPAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("WebLogUserInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("MessageID");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("RestaurantAPI.Entities.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"), 1L, 1);

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte[]>("ProductImageData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductPriceSembol")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<bool>("ProductStatus")
                        .HasColumnType("bit");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("RestaurantAPI.Entities.Reservation", b =>
                {
                    b.Property<int>("ReservationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationID"), 1L, 1);

                    b.Property<int>("ReservationCountOfPeople")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReservationCreateDate")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("ReservationEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("ReservationIsRead")
                        .HasColumnType("bit");

                    b.Property<string>("ReservationMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReservationNameSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReservationPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("ReservationStatus")
                        .HasColumnType("int");

                    b.Property<string>("WebLogUserGeo")
                        .IsRequired()
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("WebLogUserIPAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("WebLogUserInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("ReservationID");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("RestaurantAPI.Entities.Service", b =>
                {
                    b.Property<int>("ServiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceID"), 1L, 1);

                    b.Property<string>("ServiceDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ServiceIconUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("ServiceStatus")
                        .HasColumnType("bit");

                    b.Property<string>("ServiceTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ServiceID");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("RestaurantAPI.Entities.Testimonial", b =>
                {
                    b.Property<int>("TestimonialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestimonialID"), 1L, 1);

                    b.Property<string>("TestimonialComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte[]>("TestimonialImage")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("TestimonialNameSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TestimonialStatus")
                        .HasColumnType("bit");

                    b.Property<string>("TestimonialTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TestimonialID");

                    b.ToTable("Testimonials");
                });

            modelBuilder.Entity("RestaurantAPI.Entities.WebLog", b =>
                {
                    b.Property<int>("WebLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WebLogID"), 1L, 1);

                    b.Property<DateTime>("WebLogDate")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("WebLogUserGeo")
                        .IsRequired()
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("WebLogUserIPAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("WebLogUserInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("WebLogID");

                    b.ToTable("WebLogs");
                });

            modelBuilder.Entity("RestaurantAPI.Entities.Product", b =>
                {
                    b.HasOne("RestaurantAPI.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RestaurantAPI.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
